### PR TITLE
Slack notifier plugin

### LINKED ISSUE #202: Integrate with Slack
Please consider an enhancement to integrate with Slack. I expect to be notified when deploys succeed and fail.

### PR DESCRIPTION
**Pull request by aballman**
Fixes #202

### CODE REVIEW

File: plugins/events.go [hunk 1]
```diff
@@ -25,6 +26,12 @@ func GetEventName(s string) transistor.EventName {
 		"release:dockerbuilder",
 		"route53",
 		"websocket",
+		"slack",
```
Comment (aballman) [inline plugins/events.go]: You can get rid of the create/update/delete/status events.
In this context, the ':' is really just used as a namespace.

The event is 'slack' and then when the action is 'create' the event will auto append them to make 'slack:create'.
You really only need a 'slack' event and a 'slack:notify' event.

File: plugins/codeamp/codeamp.go [hunk 2]
```diff
@@ -1131,6 +1136,14 @@ func (x *CodeAmp) ReleaseFailed(release *resolvers.Release, stateMessage string)
 		x.DB.Save(&re)
 	}
 
+	if x.DB.Where("id = ?", release.ProjectID).First(&project).RecordNotFound() {
+		log.WarnWithFields("project not found", log.Fields{
+			"release": release,
+		})
+	}
+
+	x.SendNotifications("FAILED", release, &project)
```
Comment (drshrey) [inline plugins/codeamp/codeamp.go]: Should releaseState be a type State instead of a regular string? Also, we shouldn't need to pass release state as a separate param since we can grab its state within the release.

File: plugins/events.go (hunk 1 above)
Comment (amoskyler) [reply plugins/events.go]: okay, great to know. I'll clean that up

File: plugins/events.go [hunk 3]
```diff
@@ -148,35 +165,49 @@ type ServiceSpec struct {
...
 }
 
+// ProjectExtension event data struct
 type ProjectExtension struct {
 	ID          string  `json:"id"`
 	Project     Project `json:"project"`
 	Environment string  `json:"environment"`
 }
 
+// NotificationExtension event data struct
```
Comment (drshrey) [inline plugins/events.go]: Rather than create a new struct, could we add `Release` into the ProjectExtension struct? I'm not sure if there's anything fundamentally different about a notification to justify a new struct.

File: plugins/events.go (hunk 1 above)
Comment (amoskyler) [reply plugins/events.go]: Actually there are a couple of places I use something like: ```if e.Name != plugins.GetEventName("slack:notify") {
		return nil
	}```

File: plugins/slack/slack.go [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+}
+
+// Subscribe to events
+func (x *Slack) Subscribe() []string {
+	return []string{
+		"slack:create",
+		"slack:update",
+		"slack:delete",
+		"slack:status",
+		"slack:notify",
```
Comment (drshrey) [inline plugins/slack/slack.go]: What's the need for a new action i.e. `slack:notify`?

File: plugins/slack/slack.go [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+
+	payload := slack.Message{
+		Text:      fmt.Sprintf("Installed slack webhook to %s/%s", ePayload.Environment, ePayload.Project.Repository),
+		UserName:  "Codeamp",
+		Channel:   fmt.Sprintf("#%s", channel),
+		IconEmoji: fmt.Sprintf(":rocket:"),
+	}
+
+	webHookErr := sendSlackMessage(webhook, payload)
+
```
Comment (drshrey) [inline plugins/slack/slack.go]: remove the extra space here

File: plugins/events.go (hunk 1 above)
Comment (drshrey) [inline plugins/events.go]: We shouldn't need to add all the possible action combos with the supported plugins. `slack` should be enough. We should also remove `release:dockerbuilder` ->`dockerbuilder` and `project:kubernetes:deployment`->`kubernetes`. @aballman, confirming this makes sense

Comment (drshrey) [reply plugins/events.go]: We could either modify `GetEventName` or have a func similar to what we have in transistor that does a regex match with supported events

Comment (aballman) [reply plugins/events.go]: I talked with Saso about the naming thing.
It makes more sense visually, but there are certain listeners waiting for all `release` events and if it's not `release:dockerbuilder` then there's no way of receiving all `release` events.

File: plugins/slack/slack.go (hunk 5 above)
Comment (aballman) [reply plugins/slack/slack.go]: Which space? This file passes gofmt. What don't you like @drshrey ?

File: plugins/slack/slack.go (hunk 4 above)
Comment (aballman) [reply plugins/slack/slack.go]: I'm with @drshrey  on this one, but the reverse. What's `slack` being used for? I only see `slack:notify`. If you aren't creating a `slack` event directly you don't need to register it separately.

File: plugins/codeamp/codeamp.go (hunk 2 above)
Comment (amoskyler) [reply plugins/codeamp/codeamp.go]: It could be, however I want the ability to configure the messages from within codeamp. So string makes the most sense.

File: plugins/events.go (hunk 3 above)
Comment (amoskyler) [reply plugins/events.go]: We could, however there is a good chance notifications will diverge in the future. I don't think it makes sense to attach a Release to ProjectExtensions, as they are two distinct things, and ProjectExtension will never have releases associated to it.

File: plugins/codeamp/codeamp.go (hunk 2 above)
Comment (drshrey) [reply plugins/codeamp/codeamp.go]: Makes sense, and this is a generic function usable for any resource, so it doesn't make sense to derive state from something specific like Release.
