### PR TITLE
Slack Notifications for Automated Releases

### LINKED ISSUE #389: Deploy Notifications Not Triggered for Continuous Deploy
**Describe the bug**
When a user creates a deployment/release we send a message to any notification plugins. In the case of it being an automated deployment, we don't send this message.

### PR DESCRIPTION
**Pull request by aballman**
Fixes #389
* Fixes 'user' issue with slack notifications.
* Quiets down Gitsync output
* Migrations will report elapsed time to console

### CODE REVIEW

File: plugins/codeamp/codeamp.go [hunk 1]
```diff
@@ -25,8 +25,12 @@ import (
 	"github.com/jinzhu/gorm"
 	_ "github.com/jinzhu/gorm/dialects/postgres"
 	"github.com/spf13/viper"
+
+	uuid "github.com/satori/go.uuid"
 )
 
+const ContinuousDeployUUID = "59ee0229-9814-4d9b-be83-7921fe6069c1"
```
Comment (amoskyler) [inline plugins/codeamp/codeamp.go]: Can you please leave a comment on this to explain it's function?

File: plugins/gitsync/gitsync.go [hunk 2]
```diff
@@ -161,41 +153,32 @@ func (x *GitSync) commits(project plugins.Project, git plugins.Git) ([]plugins.G
...
 	}
 
-	log.Debug(string(output))
-
 	output, err = x.git(env, "-C", repoPath, "log", "--first-parent", "--date=iso-strict", "-n", "50", "--pretty=format:%H#@#%P#@#%s#@#%cN#@#%cd", git.Branch)
 
 	if err != nil {
 		log.Error(err)
-		return nil, err
+		return nil, err
```
Comment (amoskyler) [inline plugins/gitsync/gitsync.go]: plz
